package domain

import "time"

const (
	CloudProjectStatusActive   = "active"
	CloudProjectStatusArchived = "archived"

	CloudManifestStatusCommitted = "committed"

	CloudObjectStatusActive   = "active"
	CloudObjectStatusReplaced = "replaced"
	CloudObjectStatusDeleted  = "deleted"

	CloudSyncSessionStatusAuthorized = "authorized"
	CloudSyncSessionStatusCommitted  = "committed"
	CloudSyncSessionStatusExpired    = "expired"
)

// CloudProject is the server-side anchor for one Walnut project in cloud storage.
// ClientProjectID is the stable project id generated by PC Core; ID is server-owned.
type CloudProject struct {
	ID              string    `json:"id" gorm:"primaryKey;size:40"`
	UserID          string    `json:"user_id" gorm:"size:40;index;uniqueIndex:idx_cloud_project_user_client"`
	ClientProjectID string    `json:"client_project_id" gorm:"size:128;index;uniqueIndex:idx_cloud_project_user_client"`
	Name            string    `json:"name" gorm:"size:255"`
	Status          string    `json:"status" gorm:"size:16;default:'active';index"`
	LastManifestID  string    `json:"last_manifest_id" gorm:"size:40;index"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// CloudManifest records an authoritative project sync commit.
type CloudManifest struct {
	ID              string     `json:"id" gorm:"primaryKey;size:40"`
	UserID          string     `json:"user_id" gorm:"size:40;index"`
	CloudProjectID  string     `json:"cloud_project_id" gorm:"size:40;index"`
	ClientProjectID string     `json:"client_project_id" gorm:"size:128;index"`
	ManifestHash    string     `json:"manifest_hash" gorm:"size:128;index"`
	ManifestVersion int        `json:"manifest_version"`
	ObjectCount     int        `json:"object_count"`
	TotalBytes      int64      `json:"total_bytes" gorm:"index"`
	Status          string     `json:"status" gorm:"size:16;default:'committed';index"`
	SyncSessionID   string     `json:"sync_session_id" gorm:"size:40;index"`
	IdempotencyKey  string     `json:"idempotency_key" gorm:"uniqueIndex;size:160"`
	CreatedAt       time.Time  `json:"created_at"`
	CommittedAt     *time.Time `json:"committed_at"`
}

// CloudObject is object metadata owned by the billing/cloud-storage server.
// ObjectKey is provider-neutral and never derived from a local absolute path.
type CloudObject struct {
	ID              string    `json:"id" gorm:"primaryKey;size:40"`
	UserID          string    `json:"user_id" gorm:"size:40;index"`
	CloudProjectID  string    `json:"cloud_project_id" gorm:"size:40;index"`
	ClientProjectID string    `json:"client_project_id" gorm:"size:128;index"`
	ManifestID      string    `json:"manifest_id" gorm:"size:40;index"`
	ResourceID      string    `json:"resource_id" gorm:"size:255;index"`
	ResourceKind    string    `json:"resource_kind" gorm:"size:64;index"`
	ObjectKey       string    `json:"object_key" gorm:"uniqueIndex;size:512"`
	ContentHash     string    `json:"content_hash" gorm:"size:128;index"`
	SizeBytes       int64     `json:"size_bytes" gorm:"index"`
	ContentType     string    `json:"content_type" gorm:"size:128"`
	Status          string    `json:"status" gorm:"size:16;default:'active';index"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// CloudSyncSession records an upload authorization that must be consumed by a
// later manifest commit. It keeps billing as the control plane while object
// bytes stay with the object storage provider.
type CloudSyncSession struct {
	ID                  string     `json:"id" gorm:"primaryKey;size:40"`
	UserID              string     `json:"user_id" gorm:"size:40;index"`
	CloudProjectID      string     `json:"cloud_project_id" gorm:"size:40;index"`
	ClientProjectID     string     `json:"client_project_id" gorm:"size:128;index"`
	Provider            string     `json:"provider" gorm:"size:64;index"`
	ResourceFingerprint string     `json:"resource_fingerprint" gorm:"size:128;index"`
	RequestedBytes      int64      `json:"requested_bytes" gorm:"index"`
	UsedBytes           int64      `json:"used_bytes"`
	QuotaBytes          int64      `json:"quota_bytes"`
	Status              string     `json:"status" gorm:"size:16;default:'authorized';index"`
	ManifestID          string     `json:"manifest_id" gorm:"size:40;index"`
	ExpiresAt           time.Time  `json:"expires_at" gorm:"index"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	CommittedAt         *time.Time `json:"committed_at"`
}
